version: '3'

services:
    linkapi-mongodb:
        image: mongo:latest
        container_name: linkapi-mongodb
        restart: always
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - ./docker/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js:ro
            - ./docker/mongo-volume:/data/db
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    linkapi-redis:
        image: redis
        container_name: linkapi-redis
        restart: always
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - '${REDIS_PORT}:6379'
